name: libconnect
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Font and icon
  google_fonts: ^8.0.0

  # Route management
  go_router: ^17.0.1

  # State management
  get: ^4.7.3

  # Storage
  get_storage: ^2.1.1

    # HTTP requests
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


# Images
  assets:
      - assets/images/branding/